### ISSUE TITLE
Floating footer over content of page

### ISSUE THREAD

**Issue by edwinv** [mperham/sidekiq#2411]
I've reported this issue before by mail, but after the last release the issue is present again. The floating footer in de Sidekiq web UI is always hovering over the bottom part of the page. This makes a lot of actions unavailable because the buttons are always on the bottom of the page.

I'd love to see a quick fix and release for this bug, the Sidekiq web interface is mostly useless with this bug.

Screenshot with page scrolled all the way down, no buttons in screen:

![sidekiq_pro_and_new_issue_ _mperham_sidekiq](https://cloud.githubusercontent.com/assets/563294/8404030/2de046c0-1e4a-11e5-9506-5854451ea1ce.png)

**Comment by davydovanton** [comment]
@edwinv hello!
I understand right that you have long redis db url?

**Comment by edwinv** [comment]
@davydovanton 70 characters long. We use an Amazon AWS internal hostname to connect to Redis.

**Comment by davydovanton** [comment]
@edwinv and which version of sidekiq are you use?

**Comment by edwinv** [comment]
```
Sidekiq v3.4.1 / Sidekiq Pro v2.0.3
```

**Comment by mperham** [comment]
Can you try master?  I believe we fixed it to use `overflow: hidden` recently.

**Comment by edwinv** [comment]
Master doesn't solve the issue. The issue seems to be a `max-width` in a responsive version:

```css
@media (min-width: 1200px) {
  .redis-url {
    max-width: 540px;
  }
}
```

540px is too wide, when I lower this to 480px the issue is solved. Not tested for the other media queries.

**Comment by edwinv** [comment]
Fix confirmed, thanks for the prompt action!
