### ISSUE TITLE
Web UI broken since 4.2.0 ("no route" on 4.2.0, infinite loop on 4.2.3)

### ISSUE THREAD

**Issue by davidstosik** [mperham/sidekiq#3207]
Ruby version: 2.1.7p400
Sidekiq / Pro / Enterprise version(s): In the process of updating from 3.2.6 to 4.2.3, also tried 4.1.4 and 4.2.0 to confirm problem.
Rails version: 4.0.13

Hello,

We are in the process of updating Sidekiq on our app, from 3.2.6, where things seem to work correctly (at least Web UI works, Sidekiq consumes and runs jobs, etc).

Here is the configuration we've been using so far:

``` rb
#config/routes.rb
require 'sidekiq/web'
MyApp::Application.routes.draw do
  authenticate :user, lambda {|u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  #(...)
end
```

We're using Devise, and `User#admin?` is a custom method that checks a user's roles. (I just noticed that a logged out user will get redirected from `/sidekiq` to `/sidekiq/account/login`, but that was not a big deal for us).
1. As recommended in the documentation, I first updated to the latest 3.x, checked for deprecation warnings, checked if Sidekiq was still working, then moved on to the next step.
2. I updated Sidekiq to 4.2.3, then started to experience infinite redirect loops on `/sidekiq` and `/sidekiq/` (while I'm already logged in).
3. I then tried to go back to Sidekiq 4.1.4 (and not other change in our previously working configuration). This time Web UI works properly.
4. Just to confirm, I finally tried with Sidekiq 4.2.0, to experience a "No route matches /sidekiq" error message.
5. I also tried, while on 4.2.3, to experiment with a few config options I grabbed here and there while looking for people having a similar redirect loop issue, but nothing worked.

As the changelog says to open an issue if the app stops working at 4.2.0, here I am!

Thanks for reading, and thank you in advance for your help.

Edit: even on 4.1.4, if I'm logged out and try to access `/sidekiq`, I get into an infinite redirect loop.

**Comment by inkstak** [comment]
I got the same problem few weeks ago. But, as I don't remember which bug was the cause, please check both following points:

1 - The `SERVER_NAME` header sent by your webserver (nginx?)

The new `Sidekiq::Web` is built with `Rack::Builder`, which uses `Rack::URLMap` to map endpoints, which performs a check [here](https://github.com/rack/rack/blob/master/lib/rack/urlmap.rb#L54) between `SERVER_NAME` and `HTTP_HOST` headers.

Be sure that your webserver send you the same value in `SERVER_NAME` and `HTTP_HOST`.
Nginx may be using the catch-all `_` config - [read more](http://nginx.org/en/docs/http/server_names.html)

Heroku already send the good header, for example.
I have to ask my cloud provider (CleverCloud) so fix it.

2 - Your session cookies

If you use wildcard domains like me, you may encounter the [duplicate cookie issue](https://github.com/mperham/sidekiq/issues/3180).

Look at you browser console: do you see two cookies for the same domain ?

To fix it, you may disable the default sessions for `Sidekiq::Web`.
The devise's method `authenticate` take the lead to instantiate the session with your Rails session config.

```
# config/routes.rb
require 'sidekiq/web'
Sidekiq::Web.disable :sessions

MyApp::Application.routes.draw do
  authenticate :user, lambda {|u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end
```

**Comment by mperham** [comment]
It would be a big help if you could supply a tiny app which reproduces this issue.

**Comment by mperham** [comment]
Fixed on master, could you verify please?

**Comment by davidstosik** [comment]
@mperham Thank you. Unfortunately, this is still not working in my initial configuration.
I'd like to inform you though that this is not a problem for me anymore, as the issue seems to have vanished after a general update of the gems we're using (most noticeable is updating Rails from 4.0.13 to 4.2.7.1).
