### ISSUE TITLE
Sidekiq Batches aren't compatible with ActiveJob retrying

### ISSUE THREAD

**Issue by isaacseymour** [mperham/sidekiq#3373]
Ruby version: 2.3.3
Sidekiq / Pro / Enterprise version(s): 4.2.7 / 3.4.0 / no Enterprise.

I'm seeing the issue described in #2855, and I _suspect_ it's because we have custom retry logic for the in-batch jobs. i.e.:

```ruby
class StartJob < ActiveJob::Base
  def perform
    batch = Sidekiq::Batch.new
    batch.jobs do
      SomeModel.find_each { |model| InnerJob.perform_later(id: model.id) }
    end
  end
end

class InnerJob < ActiveJob::Base
  retry_on NetworkError, retries: 10, wait: 1.minute

  def perform(id:)
    # Do some network stuff
  end
end
```

We then regularly end up with jobs where it seems like everything has completed, but there are still a few jobs left pending. I suspect (although not sure how to prove it) that these are jobs where there's been a network error, which gets retried by ActiveJob like [this](https://github.com/rails/rails/blob/8b5c04e423cbfd90a15ed6fbab3f111803bc6544/activejob/lib/active_job/exceptions.rb#L27-L32), and is therefore just enqueuing a new job, not linked to the batch.

However I'm surprised that this leaves jobs pending in Sidekiq - to Sidekiq it should look like the original job succeeded, and just enqueued a new unrelated one (which is also an issue!)

Do you have any thoughts on a better way to get silent retries with ActiveJob+Batches?

**Comment by mperham** [comment]
Correct, AJ retries won't work with many of Sidekiq's features.  You'll need to use the native APIs.  AJ discards the entire current job payload and creates a new one when retrying, which discards a lot of state/metadata used by those features, including the BID.

**Comment by isaacseymour** [comment]
Ok, that makes sense. Am I correct that this is what's causing the pending count on the batch to become incorrect? If so, could you explain why that's happening?

**Comment by mperham** [comment]
I believe so.  AJ doesn't retry the exact same job, it creates a copy of the job with the same AJ metadata but they don't preserve the Sidekiq metadata.  The new job is not associated with the batch so, even though the work is retried and finished, the batch is never updated to reflect that finished work.

**Comment by mperham** [comment]
I will update the AJ wiki page to warn people that the commercial features aren't designed to work with AJ.

**Comment by isaacseymour** [comment]
But surely the original job that AJ-fails actually "succeeds" as far as Sidekiq is concerned, so should be marked as finished in the batch. I don't quite see how an AJ retry will leave a handful of jobs pending in the batch?

**Comment by mperham** [comment]
¯\_(ツ)_/¯

If it works with the native API but doesn't with AJ, there's an incompatibility somewhere.  I've opened this issue:

https://github.com/rails/rails/issues/28347

**Comment by isaacseymour** [comment]
So I'm not totally convinced that it _would_ work with the native API. It would be really helpful to have a wiki page about things that can cause batches to have phantom pending jobs left over; from going through old issues I've found mentions of:
- adding jobs twice on initial setup (i.e. two calls to `Sidekiq::Batch#jobs`)
- adding jobs except in a job that is part of the batch

I've gone through our code and am pretty convinced we're not doing either of these. Are there any other common mistakes with batches I should be looking for?

**Comment by isaacseymour** [comment]
Actually, looks like the underlying issue _may_ have been #3371. Was Pro 3.4.0 one of the versions with the bug fixed in 3.4.5?

**Comment by mperham** [comment]
Nope, the bug was introduced in 3.4.3 and fixed in 3.4.5.

**Comment by isaacseymour** [comment]
Ok, I've stopped using ActiveJob retries, updated sidekiq&sidekiq-pro, and this is still happening. Batch of ~80k jobs has 14 left pending, and there's no enqueued/processing jobs.

Sidekiq 4.2.9
Sidekiq Pro 3.4.5

Not using any uniqueness plugins.

**Comment by mperham** [comment]
Can you give me an app which repros the problem, like in #3371?
