### ISSUE TITLE
Deprecation warning with redis-4.6.0

### ISSUE THREAD

**Issue by AkashHC13** [mperham/sidekiq#5169]
Ruby version: ruby 3.0.2
Rails version: Rails 7.0.1
Sidekiq / Pro / Enterprise version(s):

Please include your initializer, sidekiq.yml, and any error message with the full backtrace.

```yml
:concurrency: 2
:queues:
  - default
 ```

Sidekiq.rb
```ruby
require 'sidekiq/web'
require 'sidekiq/cron/web'

Sidekiq.configure_server do |config|
  config.redis = { url: ENV['REDIS_URL'] }
  schedule_file = Rails.root.join('config/schedule.yml')
  Sidekiq::Cron::Job.load_from_hash! YAML.load_file(schedule_file) if File.exist?(schedule_file)
end
```
I see the following deprecation warning with redis 4.6.0
<img width="1247" alt="image" src="https://user-images.githubusercontent.com/21243624/152158462-b715a8a2-6552-46d6-b645-5b1532a7fe32.png">

**Comment by mperham** [comment]
fixed in 6.4.

**Comment by crhampton1** [comment]
@mperham, also still seeing in 6.4. Thanks!

**Comment by mperham** [comment]
Ah, right, this was fixed right after 6.4.0 was released so it'll be in 6.4.1 coming soon.

**Comment by blackst0ne** [comment]
@mperham 

Any ETA if 6.4.1?

**Comment by nickrivadeneira** [comment]
I was still getting deprecation warnings on HEAD so I opened #5173

**Comment by mperham** [comment]
And that's why I generally wait a day or two! 😂 Let the code settle... 6.4.1 coming Monday.

**Comment by Pifoupif** [comment]
> And that's why I generally wait a day or two! 😂 Let the code settle... 6.4.1 coming Monday.

Which monday :laughing: ?

**Comment by artplan1** [comment]
@Pifoupif
6.4.1 was released this monday ;)
https://rubygems.org/gems/sidekiq/versions/6.4.1
https://github.com/mperham/sidekiq/releases/tag/v6.4.1
